% I = IMAGE

% VISITED = EVERTHING IN I BELOW T_LOW

% CURRENT = FIND 1ST NOT VISITED ABOVE T_HIGH

% START SEARCHING FOR EDGE

% 	MARK CURRENT AS VISITED

% 	FIND PREV + NEXT ALONG GRADIENT

% 	IF CURRENT IS BIGGER THAN NEXT:
% 		MARK AS EDGE

% 		FIND NEXT STEP:
% 			NEXT_STEP = PERPINDICULAR TO GRADIENT
% 			IF NEXT_STEP HAS BEEN VISITED ALREADY OR IS LESS THAN T_LOW
% 				BREAK OUT OF LINE FOLLOWING, FIND A NEW POINT > T_HIGH
% 			ELSE:
% 				GO BACK TO SEARCHING FOR EDGE, EVALUATE NEW CURRENT


% 	IF CURRENT ISNT BIGGER:
% 		FIND NEXT STEP:
% 			NEXT STEP IS UP GRADIENT
% 			CURRENT = NEXT STEP
% 			GO BACK TO SEARCHING FOR EDGE, EVAL NEW CURRENT

% KEEP DOING THIS UNTIL THERE ARE NO MORE UNVISITED POINTS ABOVE T_HIGH