% I = IMAGE

% VISITED = EVERTHING IN I BELOW T_LOW

% CURRENT = FIND 1ST NOT VISITED ABOVE T_HIGH

% START SEARCHING FOR EDGE

% 	MARK CURRENT AS VISITED

% 	FIND PREV + NEXT ALONG GRADIENT

% 	IF CURRENT IS BIGGER THAN NEXT:
% 		MARK AS EDGE

% 		FIND NEXT STEP:
% 			NEXT_STEP = PERPINDICULAR TO GRADIENT
% 			IF NEXT_STEP HAS BEEN VISITED ALREADY OR IS LESS THAN T_LOW
% 				BREAK OUT OF LINE FOLLOWING, FIND A NEW POINT > T_HIGH
			

% 	IF CURRENT ISNT LARGEST:
% 		FIND NEXT STEP:
% 			GO UP GRADIENT
% 			CURRENT = NEXT STEP

% KEEP DOING THIS UNTIL THERE ARE NO MORE UNVISITED POINTS ABOVE T_HIGH